In [ ]:
#Install NumPy in your Python environment using pip, then create a Python file called insta_likes.py and import numpy as np at the top.

!pip install numpy
import numpy as np

In [10]:
#Create a NumPy array called followers using np.array() that stores the follower counts for 5 Instagram influencers: [1200, 15000, 67000, 340000, 1250000]. Print the array, its shape, number of dimensions, and data type.
import numpy as np
followers = np.array([1200,15000,67000,340000,1250000])
print(followers)
print(followers.shape)
print(followers.ndim)
print(followers.dtype)

[   1200   15000   67000  340000 1250000]
(5,)
1
int64


In [11]:
#Use np.arange() to generate an array of order IDs for 10 consecutive Zomato orders starting from 101. Print the array and its size.
arr = np.arange(101,111)
print(arr)
print(arr.size)

[101 102 103 104 105 106 107 108 109 110]
10


In [12]:
#Create a 3x3 NumPy array using np.eye() to represent a 'like' identity matrix for a new Spotify playlist feature. Print the matrix and explain what the diagonal values represent in a comment.
arr = np.eye(3,3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [2]:
#Convert a Python list of cricket scores [45, 67, 120, 89, 54] to a NumPy array, then use the .itemsize attribute to print how many bytes each score takes in memory.<br><br><em><strong>Hint:</strong> Use np.array() for conversion and .itemsize for memory size.</em>
import numpy as np
list1 = [45,67,120,89,54]
arr = np.array(list1)
print(arr)
print(arr.itemsize)

[ 45  67 120  89  54]
8
